JS105: Javascripts_Array_remove_elements_from_an_array
nicquintos/nqjstraining pull request #28
Opened 2024-08-26 07:52 UTC by nicquintos

JS105: Remove Elements from an Array

2024-10-24 14:08 UTC, chemagaton24 commented on script.js
> +let shipping = orderQueue.shift();
Can we change this to `const` since this variable is not reassigned?
```suggestion
const shipping = orderQueue.shift();
```

2024-10-24 14:09 UTC, chemagaton24 commented on script.js
> +let cancelled = orderQueue.pop();
Same goes here
```suggestion
const cancelled = orderQueue.pop();
```

2024-10-24 14:09 UTC, chemagaton24 requested changes
Can you put all your files in in a folder that correlates with their training name. To avoid conflicts of files with your other training challenge

Like so
training_name/index.html
training_name/scripts

2025-02-03 05:29 UTC, arvin-viar approved these changes
LGTM!

2025-02-03 05:30 UTC, merged