JS202:Getting_handled_on_the_dom_return_element_using_css_selectors
nicquintos/nqjstraining pull request #38
Opened 2024-09-05 11:06 UTC by nicquintos

JS202: Return Elements using CSS Selectors

2024-10-28 05:30 UTC, chemagaton24 commented on app.js
> +var navigationLinks = document.querySelectorAll("nav li a");
```suggestion
const navigationLinks = document.querySelectorAll("nav li a");
```

2024-10-28 05:30 UTC, chemagaton24 commented on app.js
> +var galleryLinks = document.querySelectorAll('#gallery li a');
```suggestion
const galleryLinks = document.querySelectorAll('#gallery li a');
```

2024-10-28 05:30 UTC, chemagaton24 commented on app.js
> +var footerImages = document.querySelectorAll('footer img');
```suggestion
const footerImages = document.querySelectorAll('footer img');
```

2025-02-03 06:27 UTC, arvin-viar requested changes
Please address code change request

2025-02-03 06:27 UTC, arvin-viar commented on JS1068_JS202_Getting_handled_onthe_DOM_challenge3/index.html
> +    <link rel="stylesheet" href="css/responsive.css">
remove import for files not included

2025-02-03 06:27 UTC, arvin-viar commented on JS1068_JS202_Getting_handled_onthe_DOM_challenge3/index.html
> +    <link rel="stylesheet" href="css/normalize.css">
remove import for files not included

2025-02-03 06:51 UTC, arvin-viar approved these changes
LGTM!

2025-02-03 06:51 UTC, merged