JS203_Traversing_DOM_event_delegation
nicquintos/nqjstraining pull request #41
Opened 2024-09-12 05:34 UTC by nicquintos

JS203: Event Delegation

2024-10-28 05:55 UTC, chemagaton24 commented on app.js
> +let section = document.getElementsByTagName('section')[0];
Since this didn't get reassigned, Can you change this to let?
```suggestion
const section = document.getElementsByTagName('section')[0];
```

2024-10-28 05:55 UTC, chemagaton24 requested changes
Can you put this on a folder and name it with the name of the challenge to avoid conflict when merging this to main branch with other challenges?

2025-02-03 06:40 UTC, arvin-viar requested changes
Please address code change request

2025-02-03 06:40 UTC, arvin-viar commented on JS1069_JS203_traversing_the_DOM_challenge/index.html
> +    <link rel="stylesheet" href="style.css" />
remove this line since the `style.css` file was not included

2025-02-03 06:53 UTC, arvin-viar approved these changes
LGTM!

2025-02-03 06:53 UTC, merged