JS-101_Making Decisions in Your Code with Conditional Statements_else_task
nicquintos/nqjstraining pull request #8
Opened 2024-07-10 03:31 UTC by nicquintos

Else task

2024-10-24 06:29 UTC, chemagaton24 requested changes
Can you put all your files in in a folder that correlates with their training name. To avoid conflicts of files with your other training challenge

Like so
training_name/index.html
training_name/scripts

2025-01-30 11:16 UTC, arvin-viar commented on JS-1061_Making_Decisions_in_Your_Code_with_Conditional_Statements_challenge_2_pt3/scripts.js
> +const isAdmin = true;
This should be set to `false` in order for the conditional statement to fall into `else`.

2025-01-30 11:17 UTC, arvin-viar commented on JS-1061_Making_Decisions_in_Your_Code_with_Conditional_Statements_challenge_2_pt3/scripts.js
> +const isAdmin = true;
```suggestion
const isAdmin = false;
```

2025-01-30 11:18 UTC, arvin-viar commented on JS-1061_Making_Decisions_in_Your_Code_with_Conditional_Statements_challenge_2_pt3/scripts.js
> +const isAdmin = true;
This should be set to `false` in order for the conditional statement to fall into `else`.
```suggestion
const isAdmin = false;
```

2025-01-30 11:19 UTC, arvin-viar requested changes
Please see change request.

2025-01-31 09:19 UTC, arvin-viar approved these changes
LGTM!

2025-01-31 09:19 UTC, merged